CREATE TABLE CAD_USUARIO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100),
    EMAIL VARCHAR(100),
    TELEFONE VARCHAR(20),
    SENHA VARCHAR(255),
    ST_REGISTRO CHAR(1),
    DATA_CRIACAO DATETIME DEFAULT CURRENT_TIMESTAMP
);