create table CAD_MURAL (
    ID INT auto_increment PRIMARY KEY,
    CATEGORIA CHAR(1) COMMENT 'TIPO DE SERVICO (V)ENDA (O)FERECO',
    NOME VARCHAR(100) COMMENT 'NOME PESSOA',
    EMAIL VARCHAR(100) COMMENT 'EMAIL PESSOA',
    TELEFONE VARCHAR(20) COMMENT 'TELEFONE PESSOA',
    TITULO VARCHAR(40) COMMENT 'TÍTULO PESSOA',
    DESCRICAO VARCHAR(250)  COMMENT 'DESCRICAO',
    DATA_CRIACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    ST_REGISTRO CHAR(1) COMMENT '(A)tivo e (I)nativo'
);

ALTER TABLE CAD_MURAL ADD COLUMN st_registro char(1) COMMENT '(A)tivo e (I)nativo';